name: SRP
version: 1.2
author: Jacob
main: fr.anxxitty.srp.SpeedRunPlugin
api-version: 1.16
softdepend: [Multiverse-Core, Multiverse-NetherPortals]
commands:
    startrun:
        description: "Starts a speedrun."
        usage: "/startrun"
    endrun:
        description: "Ends the speedrun."
        usage: "/endrun"
    reset:
        description: "Resets the speedrun."
        usage: "/reset"